#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Apr 18 14:12:32 KST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=BSL_v10.1.1.zip
